import com.google.devtools.ksp.gradle.KspExtension
import internals.libs
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.kotlin.dsl.configure
import org.gradle.kotlin.dsl.dependencies

class AndroidKoinConventionPlugin : Plugin<Project> {
    override fun apply(target: Project) {
        with(target) {
            // Apply the KSP plugin
            pluginManager.apply("com.google.devtools.ksp")

            // Configure KSP
            extensions.configure<KspExtension> {
                arg("KOIN_CONFIG_CHECK", "true")
                arg("KOIN_DEFAULT_MODULE", "AutoGeneratedKoinModule")
            }

            // Add Koin dependencies
            dependencies {
                add("implementation", platform(libs.findLibrary("koin.bom").get()))
                add("implementation", libs.findLibrary("koin.android").get())
                add("implementation", platform(libs.findLibrary("koin.annotations-bom").get()))
                add("implementation", libs.findLibrary("koin.annotations").get())

                add("ksp",libs.findLibrary("koin.ksp.compiler").get())
                add("kspTest",libs.findLibrary("koin.ksp.compiler").get())
                add("kspAndroidTest",libs.findLibrary("koin.ksp.compiler").get())
            }
        }
    }
}
